import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import React, { useState } from "react";
import Image from "next/image";
import {
	useSession,
	signIn,
	signOut,
} from "next-auth/react";

type TechnologyCardProps = {
	name: string;
	description: string;
	documentation: string;
};

const HomeComponent = () => {
	const { data: session } = useSession();
	const myLoader = () => {
		return session?.user?.image;
	};

	if (session) {
		return (
			<div className="flex flex-col">
				<div className="flex flex-row items-center justify-center gap-1">
					Hello {session.user?.name}!
					<Image
						className="rounded-full "
						width={40}
						height={40}
						loader={myLoader as any}
						src={session.user?.image || ""}
						alt=""
					/>
				</div>
				<button
					className=" bg-amber-500 p-2 rounded m-3"
					onClick={() => signOut()}
				>
					Sign out
				</button>
				<Chat />
			</div>
		);
	}
	return (
		<>
			Not signed in
			<button
				className=" bg-amber-500 p-2 rounded m-3"
				onClick={() => signIn()}
			>
				Sign in{" "}
			</button>
		</>
	);
};

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Chattii</title>
				<meta
					name="description"
					content="Generated by create-t3-app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
				<h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold ">
					Cha<span className="text-amber-500">tt</span>ii
				</h1>

				<HomeComponent />
				{/* <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
					<br />
					{hello.data ? (
						<p>{hello.data.greeting}</p>
					) : (
						<p>Loading..</p>
					)}
				</div> */}
			</main>
		</>
	);
};

const Chat: React.FC = () => {
	const { data: session } = useSession();
	const [messages, setMessages] = useState<string>("");
	const [chat, setChat] = useState<string>("");

	const getAll = trpc.useQuery(["example.getAll"]);

	const mutation = trpc.useMutation(
		[
			"example.sendMessage", // name of the mutation
		]
		// { onSuccess: () => setMessages("") }
	);

	const sendMessage = (
		e: React.FormEvent<HTMLFormElement>
	) => {
		e.preventDefault();

		if (messages.length === 0) {
			return;
		}
		setChat(messages);

		mutation.mutate({
			content: messages,
			userName: session?.user?.name || "Anonymous",
		});

		setMessages("");

		console.log("Message sent:", messages);
	};

	return (
		<>
			<div className="p-3 min-w-full bg-slate-800 mb-4">
				{getAll.data ? (
					getAll.data.map(element => {
						return (
							<p key={element.id}>
								{element.userName + ": "}
								<span className=" text-gray-400 ">
									{element.content + "\n"}
								</span>
							</p>
						);
					})
				) : (
					<p>Loading..</p>
				)}
			</div>
			<form onSubmit={sendMessage} className="w-full flex">
				<input
					type="text"
					value={messages}
					onChange={e => setMessages(e.target.value)}
					className="text-slate-800 w-full"
				/>
				<input
					type="submit"
					value="Send"
					className=" bg-amber-500 p-2 rounded ml-2"
				/>
				{mutation.error && <p>Error: {mutation.error.message}</p>}
			</form>
		</>
	);
};

const TechnologyCard = ({
	name,
	description,
	documentation,
}: TechnologyCardProps) => {
	return (
		<section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
			<h2 className="text-lg text-gray-700">{name}</h2>
			<p className="text-sm text-gray-600">{description}</p>
			<a
				className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
				href={documentation}
				target="_blank"
				rel="noreferrer"
			>
				Documentation
			</a>
		</section>
	);
};

export default Home;
